#!/usr/bin/env bash
kill -s SIGKILL $(ps aux | grep deployer | grep bin | awk '{print $2}') && echo -e "\e[32m--> deployer killed\e[0m" && exit
echo -e "\e[101mNo deployer found, please check 'ps aux' ot 'htop' to find the deployer's PID\e[0m"
